import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      
      <body>
        
      <div className={"wrapper"} id="background">
      <Link href="/" className="header p-8">Home</Link>
      <main id="content-wrap">
      {children}
      </main>
      <footer>
      <Link href="/" className="footer" id="footer">Abel</Link>
      </footer>
      
      </div>
      </body>
    </html>
  );
}
