import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      
      <body>
      <div className={"wrapper"}>
      <Link href="/" className="header">Home</Link>
      <Link href="/" className="Footer">Abel</Link>
      <main>
      {children}
      </main>
      
      </div>
      </body>
    </html>
  );
}
